name: Master CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: josue-r
          password: ${{ secrets.JRS_TOKEN }}

      - name: List current dsirectory
        run: |
          ls -l
      
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: test1
          build-args: |
            APP_VERSION=1.0
            DB_USER=${{ secrets.STORE_DB_USERNAME }}
            DB_PASS=${{ secrets.STORE_DB_PASSWORD }}
